### ISSUE TITLE
Замечания по шаблону J4

### ISSUE THREAD

**Issue by AlekVolsk** [JPathRu/joomla-cms#5]
### Is your feature request related to a problem? Please describe.

UX admin template Joomla 4

### Describe the solution you'd like

Если мы посмотрим на изначально предполагаемый мокап, представленный в https://magazine.joomla.org/issues/issue-nov-2017/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend, то поймём, что конечный результат сильно разнится и выглядит и воспринимается гораздо хуже мокапа.

Цветовая тема регулируется в параметрах шаблона, однако 5 основных цветов - этого мало, в стилях представлено 7 основных цветов в виде css-переменных, и несколько десятков второстепенных.

Догадались сделать ч/б стиль для людей с дальтонизмом, но не догадались сделать тёмную тему, которая куда более востребована, нежели ч/б.

Шапка не стики и параметрами шаблона это не регулируется.

При открытии вида edit любого элемента компонента ряд элементов шапки становится некликабельными, но визуально это никак не выделено. Лого джумлы как ссылку на главную желательно оставить кликабельной, добавив ей `target="_blank"`.

![изображение](https://user-images.githubusercontent.com/9278339/63376713-7a43f080-c39f-11e9-84e0-313316518cf2.png)
Версии в шапке делать нечего, это техническая информация, лучше всего перенести это вниз статус бара, в свёрнутом виде показать только иконку с тултипом.

![изображение](https://user-images.githubusercontent.com/9278339/63377310-ed9a3200-c3a0-11e9-931d-89f83b91df15.png)
Кнопка post installation messages не нужна видимой постоянно - только при наличии непрочитанных сообщений. Отсутствует пункт "напомнить позже" или "отметить всё прочитанным" (последний актуально для веб-разработчиков на поточном создании сайтов на Joomla - они эти сообщения наизусть уже знают).

![изображение](https://user-images.githubusercontent.com/9278339/63377630-87fa7580-c3a1-11e9-9b72-7cea1ec16dd5.png)
Кнопка private messages действительно нужна? может, скрывать её в настройках соответствующего компонента?

![изображение](https://user-images.githubusercontent.com/9278339/63377814-dd368700-c3a1-11e9-86e4-e9b4abc56bca.png)
Закрытие всплывающего системного сообщения не закрывает блок полностью

Многоколоночный дашборд не всегда удобен, кол-во колонок необходимо регулировать настройками шаблона.

![изображение](https://user-images.githubusercontent.com/9278339/63377884-ff300980-c3a1-11e9-938e-eeee918dc295.png)
Кнопки в блоке неудобны, занимают очень много экранного места, достаточно сделать блок из двойных кнопок в ряд, каждая двойная кнопка - это более длинная кнопка с иконкой и заголовком в ряд и рядом более мелкая кнопка "+" для добавления соответствующего элемента. Точно не нужна кнопка плагинов и шаблонов. Нужна кнопка очистки кеша.

![изображение](https://user-images.githubusercontent.com/9278339/63378161-aa40c300-c3a2-11e9-9fc6-12902186c931.png)
Эти блоки по сути можно объединить. Кнопка чекина не нужна - вместо неё должен быть виджет с уже готовой информацией по состоянию сайта изнутри.

![изображение](https://user-images.githubusercontent.com/9278339/63378282-f7249980-c3a2-11e9-8da6-d71cef00bb97.png)
Контентные виджеты не нужны на общем дашборде - им место только на контентном дашборде.

На контентном дашборде неплохо бы по включённой настройке выводить статистику-счётчики, кол-во материалов/категорий/модулей, опубликованных/неопубликованных.

На дашборде меню для каждого меню вывести кнопку с выпадающим подменю со списком связанных с меню модулей, с переходом в редактирование конкретного модуля по клику.

На дашборде компонентов дать возможность не показывать некоторые компоненты на дашборде.

Если сайдбар свёрнут, то при переходе в любой пункт верхнего уровня он разворачивается и остаётся развёрнутым - при убирании курсора мыши с него свернуть бы обратно.

![изображение](https://user-images.githubusercontent.com/9278339/63379203-e2e19c00-c3a4-11e9-9556-286d8e3d5c2c.png)
В списочных видах компонентов фильтрацию и сортировку данных можно было бы убрать в правый сворачиваемый сайдбар, который открывать по кнопке в тулбаре, иначе над табличным списком он очень много места занимает на не очень больших экранах бюджетных ноутбуков - просто треть  экрана минус.

![изображение](https://user-images.githubusercontent.com/9278339/63379281-0b699600-c3a5-11e9-8224-8197b49736de.png)
Параметры в несколько колонок построчно - жутко неудобно, особенно когда имеются скрываемые параметры (с опцией `showon`), лучше бы блоки в несколько колонок, но параметры  только в одну колонку.

![изображение](https://user-images.githubusercontent.com/9278339/63379410-52578b80-c3a5-11e9-8e92-c4eb9f67bbec.png)
Разноразмерные разноцветные кнопки?

![изображение](https://user-images.githubusercontent.com/9278339/63379698-e6295780-c3a5-11e9-8351-c14383b672c8.png)
Общее деление на блоки съедает экранное место
Фон полей сливается с фоном окружения - границы полей становятся размытыми.
Фон редактора и его тулбара в фон окружения - это вообще нонсенс...

![изображение](https://user-images.githubusercontent.com/9278339/63379820-2e487a00-c3a6-11e9-8657-1c205d180fdb.png)
Кнопки редакторных плагинов спрятали, но вывели снизу под редактором большущую кнопку переключения вида редактора... Вернуть плагинные кнопки под редактор вниз! Ну или хотя бы отдельным тулбаром в ряд, а лучше в виде тулбара снизу редактора - не надо делать их лошадиного размера.

![изображение](https://user-images.githubusercontent.com/9278339/63380121-e2e29b80-c3a6-11e9-9b46-524daee00651.png)
Так выглядит `select multiple="true"`, у которого нельзя убрать выделение со всех опций.

![изображение](https://user-images.githubusercontent.com/9278339/63381449-c136e380-c3a9-11e9-97f3-2210dbaf1480.png)
Поле типа number не завёрстано.

![изображение](https://user-images.githubusercontent.com/9278339/63380277-3523bc80-c3a7-11e9-9222-c83e6ab4b323.png)
Поле subform repeatable (не table) вообще не завёрстано. Нет слоя для subform с табами слева, хотя табы слева применяются в permissions.

![изображение](https://user-images.githubusercontent.com/9278339/63380594-f2161900-c3a7-11e9-82d1-951273480c40.png)
Что за странная обводка вокруг кнопки подменю? неужели нельзя просто выделить её фоном?

![изображение](https://user-images.githubusercontent.com/9278339/63380764-4620fd80-c3a8-11e9-9edb-2e832149e84c.png)
В медиа-менеджере нет поля указания относительного пути. Информация о выделенном файле не высвечивается. Для одного поля image позволяется выбрать несколько картинок?

![изображение](https://user-images.githubusercontent.com/9278339/63381018-db23f680-c3a8-11e9-80eb-ac129d2ca772.png)
button-group более недоступен?

### Additional context

Аякс-сохранение элементов и и аякс-пагинация были бы уместны на пороге 2020-го.

**Comment by AlekVolsk** [comment]
![изображение](https://user-images.githubusercontent.com/9278339/63383834-926f3c00-c3ae-11e9-97e5-ee1dabe39b88.png)
Как вам такой вариант?

**Comment by zikkuratvk** [comment]
Ага причем некоторые косяки тянутся с первой беты, видно что не работают над вылизыванием вообще.

Если честно я не понимаю, почему нельзя просто следовать дизайн проекту, фактически они стараются остаться в тех же расширениях, что у них были в 3-ке хотя большая часть из них бесполезны и устарели.

**Comment by b2z** [comment]
> Цветовая тема регулируется в параметрах шаблона, однако 5 основных цветов - этого мало, в стилях представлено 7 основных цветов в виде css-переменных, и несколько десятков второстепенных.

Надо вынести все цвета в настройки? Не будет ли перебор?

> но не догадались сделать тёмную тему, которая куда более востребована, нежели ч/б.

Типа такую же переключалку?

> Шапка не стики и параметрами шаблона это не регулируется.

А нужно ли стики? Там иконок не так много, и они не часто используемые. Плюс стики остаются кнопки.

> Версии в шапке делать нечего, это техническая информация, лучше всего перенести это вниз статус бара

Согласен.

> в свёрнутом виде показать только иконку с тултипом.

Поясни, не понял этот момент.

> Лого джумлы как ссылку на главную желательно оставить кликабельной, добавив ей target="_blank".

Лого слева? Оно ведёт на главную админки.

> При открытии вида edit любого элемента компонента ряд элементов шапки становится некликабельными, но визуально это никак не выделено. 

Странно, у меня иконки становятся блеклыми.

> Кнопка post installation messages не нужна видимой постоянно - только при наличии непрочитанных сообщений. 

Согласен.

> Отсутствует пункт "напомнить позже" или "отметить всё прочитанным" (последний актуально для веб-разработчиков на поточном создании сайтов на Joomla - они эти сообщения наизусть уже знают).

Что ещё за "напомнить позже"? "отметить всё прочитанным" - согласен

> Кнопка private messages действительно нужна? может, скрывать её в настройках соответствующего компонента?

Согласен

> Закрытие всплывающего системного сообщения не закрывает блок полностью

Как воспроизвести?

> Многоколоночный дашборд не всегда удобен, кол-во колонок необходимо регулировать настройками шаблона.

Как вариант

> Кнопки в блоке неудобны, занимают очень много экранного места

Согласен

> Точно не нужна кнопка плагинов и шаблонов. Нужна кнопка очистки кеша.

По умолчанию? Спорно. А так это настраивается.

> Эти блоки по сути можно объединить. Кнопка чекина не нужна - вместо неё должен быть виджет с уже готовой информацией по состоянию сайта изнутри.

Субъективно. К обсуждению. Кнопки можно настроить. Что за состояние сайта?

> Контентные виджеты не нужны на общем дашборде - им место только на контентном дашборде.

Субъективно. К обсуждению.

> Контентные виджеты не нужны на общем дашборде - им место только на контентном дашборде.
На контентном дашборде неплохо бы по включённой настройке выводить статистику-счётчики, кол-во материалов/категорий/модулей, опубликованных/неопубликованных.
На дашборде меню для каждого меню вывести кнопку с выпадающим подменю со списком связанных с меню модулей, с переходом в редактирование конкретного модуля по клику.
На дашборде компонентов дать возможность не показывать некоторые компоненты на дашборде.

Это больше хотелки...

> Если сайдбар свёрнут, то при переходе в любой пункт верхнего уровня он разворачивается и остаётся развёрнутым - при убирании курсора мыши с него свернуть бы обратно.

Скакать будет, не?

> Если сайдбар свёрнут, то при переходе в любой пункт верхнего уровня он разворачивается и остаётся развёрнутым - при убирании курсора мыши с него свернуть бы обратно.

> В списочных видах компонентов фильтрацию и сортировку данных можно было бы убрать в правый сворачиваемый сайдбар, который открывать по кнопке в тулбаре, иначе над табличным списком он очень много места занимает на не очень больших экранах бюджетных ноутбуков - просто треть экрана минус.
Забыл, что в тройке сначала было справа, а потом сделали сверху. Обратно точно не вернут. Плюс сайдбар уже занят.

> Параметры в несколько колонок построчно - жутко неудобно, особенно когда имеются скрываемые параметры (с опцией showon), лучше бы блоки в несколько колонок, но параметры только в одну колонку.

Хмм, ок.

> Разноразмерные разноцветные кнопки?

Баг.

> Общее деление на блоки съедает экранное место

Ты про отступы?

> Фон полей сливается с фоном окружения - границы полей становятся размытыми.

Что такое фон полей?

> Фон редактора и его тулбара в фон окружения - это вообще нонсенс...

Не понял тебя...

> Кнопки редакторных плагинов спрятали, но вывели снизу под редактором большущую кнопку переключения вида редактора... Вернуть плагинные кнопки под редактор вниз! Ну или хотя бы отдельным тулбаром в ряд, а лучше в виде тулбара снизу редактора - не надо делать их лошадиного размера.

Субъективно. К обсуждению.

> Так выглядит select multiple="true", у которого нельзя убрать выделение со всех опций.
Поле типа number не завёрстано.
Поле subform repeatable (не table) вообще не завёрстано. Нет слоя для subform с табами слева, хотя табы слева применяются в permissions.

Видимо руки у них не дошли.

> Что за странная обводка вокруг кнопки подменю? неужели нельзя просто выделить её фоном?

Согласен.

> button-group более недоступен?

Кнопка должна быть справа возле поля?

> В медиа-менеджере нет поля указания относительного пути. Информация о выделенном файле не высвечивается. Для одного поля image позволяется выбрать несколько картинок?

Медиа-менеджер - это отдельная песня.

> Аякс-сохранение элементов и и аякс-пагинация были бы уместны на пороге 2020-го.

Это отдельная песня.

> Как вам такой вариант?

Плюс.

**Comment by zikkuratvk** [comment]
> Надо вынести все цвета в настройки? Не будет ли перебор?

Я так понимаю это речь про переменные из которых генерируется стили шаблона.

>> Аякс-сохранение элементов и и аякс-пагинация были бы уместны на пороге 2020-го.

> Это отдельная песня.

По моему вполне уместное желание, это реально простая функция, которая многим бы сделала хорошо.

**Comment by b2z** [comment]
> По моему вполне уместное желание, это реально простая функция, которая многим бы сделала хорошо.

 Я не спорю, но это не относится к внешнему виду шаблона. Нужна поддержка на уровне компонентов.

**Comment by AlekVolsk** [comment]
> Нужна поддержка на уровне компонентов.

Это и без компонентов легко реализуется, рокпад-едитор тому подтверждение, 20 строк для сохранения

**Comment by AlekVolsk** [comment]
> Надо вынести все цвета в настройки? Не будет ли перебор?

Хотя бы все основные, их явно больше 5, и описание, на что они влияют

> > но не догадались сделать тёмную тему, которая куда более востребована, нежели ч/б.
>
> Типа такую же переключалку?

Да

> > в свёрнутом виде показать только иконку с тултипом.
>
> Поясни, не понял этот момент.

Когда сайдбар свёрнут, версия не уместится во всю строку, показать иконку джумлы, а в подсказку к иконке вывести версию

> > Закрытие всплывающего системного сообщения не закрывает блок полностью
>
> Как воспроизвести?

Сделать сохранение любого элемента любой сущности, например материала или пункта меню

> Что за состояние сайта?

Это то, что открывается по кнопке чек-ина.


> > Если сайдбар свёрнут, то при переходе в любой пункт верхнего уровня он разворачивается и остаётся развёрнутым - при убирании курсора мыши с него свернуть бы обратно.
> 
> Скакать будет, не?

А это как заверстают


> > Общее деление на блоки съедает экранное место
> 
> Ты про отступы?

Да, отступы, бордеры


> > Фон полей сливается с фоном окружения - границы полей становятся размытыми.
> 
> Что такое фон полей?

background-color элементов типа input, select, textarea



> > Фон редактора и его тулбара в фон окружения - это вообще нонсенс...
> 
> Не понял тебя...

Белый редактор на фоне белого блока



> > button-group более недоступен?
> 
> Кнопка должна быть справа возле поля?

да

**Comment by b2z** [comment]
> Сделать сохранение любого элемента любой сущности, например материала или пункта меню

У меня всё ок...

> Белый редактор на фоне белого блока

Так бэк же серый.

Если что, более мелкие иконки продавливаем здесь:
https://github.com/joomla/joomla-cms/pull/25865

**Comment by b2z** [comment]
А ну и уже по шаблону бомбят :)
https://github.com/joomla/joomla-cms/issues?q=is%3Aissue+is%3Aopen+label%3A%22J4+Backend+Template%22

**Comment by AlekVolsk** [comment]
> > Сделать сохранение любого элемента любой сущности, например материала или пункта меню
> 
> У меня всё ок...

firefox попробуй
